// Generated by CoffeeScript 1.8.0
(function() {
  var ANDROID_RELATIONS, IM_VENDORS, PHONETIC_FIELDS, VCardParser, capitalizeFirstLetter, getAndroidItem, quotedPrintable, regexps, utf8,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __slice = [].slice;

  if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
    utf8 = require('utf8');
    quotedPrintable = require('quoted-printable');
  } else {
    utf8 = window.utf8;
    quotedPrintable = window.quotedPrintable;
  }

  regexps = {
    begin: /^BEGIN:VCARD$/i,
    end: /^END:VCARD$/i,
    beginNonVCard: /^BEGIN:(.*)$/i,
    endNonVCard: /^END:(.*)$/i,
    simple: /^(version|fn|n|title|org|note|categories|bday|url)(;CHARSET=UTF-8)?(;ENCODING=QUOTED-PRINTABLE)?\:(.+)$/i,
    composedkey: /^item(\d{1,2})\.([^\:]+):(.+)$/,
    complex: /^([^\:\;]+);([^\:]+)\:(.+)$/,
    property: /^(.+)=(.+)$/,
    extended: /^X-([^\:]+)\:(.+)$/i,
    applebday: /^(version|fn|n|title|org|note|categories|bday|url);value=date:(.+)$/i,
    android: /^x-android-custom\:(.+)$/i
  };

  IM_VENDORS = ['skype', 'skype-username', 'aim', 'msn', 'yahoo', 'qq', 'google-talk', 'gtalk', 'icq', 'jabber', 'sip'];

  PHONETIC_FIELDS = ['phonetic-first-name', 'phonetic-middle-name', 'phonetic-last-name'];

  ANDROID_RELATIONS = ['custom', 'assistant', 'brother', 'child', 'domestic partner', 'father', 'friend', 'manager', 'mother', 'parent', 'partner', 'referred by', 'relative', 'sister', 'spouse'];

  capitalizeFirstLetter = function(string) {
    return "" + (string.charAt(0).toUpperCase()) + (string.toLowerCase().slice(1));
  };

  getAndroidItem = function(type, key, value) {
    var index, length, prefix;
    key = key.toLowerCase().replace('_', ' ');
    if (key === 'anniversary') {
      index = 1;
    } else if (key === 'died') {
      index = 2;
    } else {
      index = 0;
      length = ANDROID_RELATIONS.length;
      while (index < length && ANDROID_RELATIONS[index] !== key) {
        index++;
      }
      if (index === length) {
        key = null;
      }
    }
    if (key) {
      prefix = 'X-ANDROID-CUSTOM:vnd.android.cursor.item/';
      return "" + prefix + type + ";" + value + ";" + index + ";;;;;;;;;;;;;";
    } else {
      return null;
    }
  };

  VCardParser = (function() {
    function VCardParser(vcf) {
      this.reset();
      if (vcf) {
        this.read(vcf);
      }
    }

    VCardParser.prototype.reset = function() {
      this.contacts = [];
      this.currentContact = null;
      this.currentDatapoint = null;
      this.currentIndex = null;
      return this.currentVersion = "3.0";
    };

    VCardParser.prototype.storeCurrentDatapoint = function() {
      if (this.currentDatapoint) {
        this.currentContact.datapoints.push(this.currentDatapoint);
        return this.currentDatapoint = null;
      }
    };

    VCardParser.prototype.addDatapoint = function(name, type, value) {
      this.storeCurrentDatapoint();
      return this.currentContact.datapoints.push({
        name: name,
        type: type,
        value: value
      });
    };

    VCardParser.prototype.addTypeProperty = function(dp, pvalue) {
      var oldTypeValue;
      if ('type' in dp) {
        dp.typesOther = dp.typesOther || [];
        if (pvalue === 'home' || pvalue === 'work' || pvalue === 'cell') {
          oldTypeValue = dp.type;
          dp.type = pvalue;
          return dp.typesOther.push(oldTypeValue);
        } else {
          return dp.typesOther.push(pvalue);
        }
      } else {
        return dp.type = pvalue;
      }
    };

    VCardParser.prototype.storeCurrentContact = function() {
      var _ref;
      if ((this.currentContact.n == null) && (this.currentContact.fn == null)) {
        console.error('There should be at least a N field or a FN field');
      }
      if ((this.currentContact.n == null) || ((_ref = this.currentContact.n) === '' || _ref === ';;;;')) {
        this.currentContact.n = VCardParser.fnToN(this.currentContact.fn).join(';');
      }
      if ((this.currentContact.fn == null) || this.currentContact.fn === '') {
        this.currentContact.fn = VCardParser.nToFN(this.currentContact.n);
      }
      return this.contacts.push(this.currentContact);
    };

    VCardParser.prototype.read = function(vcard) {
      var line, _i, _len, _ref, _results;
      _ref = this.splitLines(vcard);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        line = _ref[_i];
        _results.push(this.handleLine(line));
      }
      return _results;
    };

    VCardParser.prototype.splitLines = function(vcard) {
      var inQuotedPrintable, lines, sourcelines;
      sourcelines = vcard.split(/\r?\n/);
      lines = [];
      inQuotedPrintable = false;
      sourcelines.forEach(function(line) {
        var lineIndex;
        if (!((line == null) || line === '')) {
          if (line[0] === ' ' || inQuotedPrintable) {
            if (line[0] === ' ') {
              line = line.slice(1);
            }
            if (inQuotedPrintable) {
              if (line[line.length - 1] === '=') {
                line = line.slice(0, -1);
              } else {
                inQuotedPrintable = false;
              }
            }
            lineIndex = lines.length - 1;
            if (lineIndex >= 0) {
              return lines[lineIndex] = lines[lineIndex] + line;
            } else {
              return lines.push(line);
            }
          } else {
            if (/^(.+)ENCODING=QUOTED-PRINTABLE(.+)=$/i.test(line)) {
              inQuotedPrintable = true;
              line = line.slice(0, -1);
            }
            return lines.push(line);
          }
        }
      });
      return lines;
    };

    VCardParser.prototype.handleLine = function(line) {
      if (this.nonVCard) {
        if (regexps.endNonVCard.test(line)) {
          if (line.match(regexps.endNonVCard)[1] === this.nonVCard) {
            return this.nonVCard = false;
          }
        }
      } else if (regexps.begin.test(line)) {
        return this.currentContact = {
          datapoints: []
        };
      } else if (regexps.beginNonVCard.test(line)) {
        return this.nonVCard = line.match(regexps.beginNonVCard)[1];
      } else if (regexps.end.test(line)) {
        this.storeCurrentDatapoint();
        return this.storeCurrentContact();
      } else if (regexps.simple.test(line)) {
        return this.handleSimpleLine(line);
      } else if (regexps.applebday.test(line)) {
        return this.handleSimpleLine(line, true);
      } else if (regexps.android.test(line)) {
        return this.handleAndroidLine(line);
      } else if (regexps.extended.test(line)) {
        return this.handleExtendedLine(line);
      } else if (regexps.composedkey.test(line)) {
        return this.handleComposedLine(line);
      } else if (regexps.complex.test(line)) {
        return this.handleComplexLine(line);
      }
    };

    VCardParser.prototype.handleSimpleLine = function(line, apple) {
      var all, key, nParts, nPartsCleaned, quoted, utf, value, _ref, _ref1;
      if (apple == null) {
        apple = false;
      }
      if (apple) {
        _ref = line.match(regexps.applebday), all = _ref[0], key = _ref[1], value = _ref[2];
      } else {
        _ref1 = line.match(regexps.simple), all = _ref1[0], key = _ref1[1], utf = _ref1[2], quoted = _ref1[3], value = _ref1[4];
      }
      if (quoted != null) {
        value = VCardParser.unquotePrintable(value);
      }
      value = VCardParser.unescapeText(value);
      key = key.toLowerCase();
      if (key === 'version') {
        return this.currentversion = value;
      } else if (key === 'categories') {
        return this.currentContact.tags = value.split(/(?!\\),/).map(VCardParser.unescapeText);
      } else if (key === 'n') {
        nParts = value.split(/(?!\\);/);
        if (nParts.length === 5) {
          return this.currentContact['n'] = value;
        } else {
          nPartsCleaned = ['', '', '', '', ''];
          if (nParts.length < 5) {
            nParts.forEach(function(part, index) {
              return nPartsCleaned[index] = part;
            });
          } else {
            nParstCleaned[2] = nParts.join(' ');
          }
          return this.currentContact['n'] = nPartsCleaned.join(';');
        }
      } else if (key === 'title' || key === 'org' || key === 'fn' || key === 'url' || key === 'note' || key === 'bday' || key === 'url') {
        return this.currentContact[key.toLowerCase()] = value;
      }
    };

    VCardParser.prototype.handleExtendedLine = function(line, android) {
      var all, key, value, _ref;
      _ref = line.match(regexps.extended), all = _ref[0], key = _ref[1], value = _ref[2];
      if (key != null) {
        key = key.toLowerCase();
        if (__indexOf.call(IM_VENDORS, key) >= 0) {
          return this.currentContact.datapoints.push({
            name: 'chat',
            type: key,
            value: value
          });
        } else if (__indexOf.call(PHONETIC_FIELDS, key) >= 0) {
          key = key.replace(/-/g, ' ');
          return this.currentContact.datapoints.push({
            name: 'about',
            type: key,
            value: value
          });
        }
      }
    };

    VCardParser.prototype.handleAndroidLine = function(line) {
      var all, parts, raw, type, value, _ref, _ref1;
      _ref = line.match(regexps.android), all = _ref[0], raw = _ref[1];
      parts = raw.split(';');
      switch (parts[0].replace('vnd.android.cursor.item/', '')) {
        case 'contact_event':
          value = parts[1];
          type = (_ref1 = parts[2]) === '0' || _ref1 === '2' ? parts[3] : parts[2] === '1' ? 'anniversary' : 'birthday';
          return this.currentContact.datapoints.push({
            name: 'about',
            type: type,
            value: value
          });
        case 'relation':
          value = parts[1];
          type = ANDROID_RELATIONS[+parts[2]];
          if (type === 'custom') {
            type = parts[3];
          }
          return this.currentContact.datapoints.push({
            name: 'relation',
            type: type,
            value: value
          });
        case 'nickname':
          value = parts[1];
          return this.currentContact.nickname = value;
      }
    };

    VCardParser.prototype.handleComposedLine = function(line) {
      var all, itemidx, key, part, properties, value, _ref;
      _ref = line.match(regexps.composedkey), all = _ref[0], itemidx = _ref[1], part = _ref[2], value = _ref[3];
      if (this.currentIndex === null || this.currentIndex !== itemidx) {
        this.storeCurrentDatapoint();
        this.currentDatapoint = {};
      }
      this.currentIndex = itemidx;
      part = part.split(';');
      key = part[0];
      properties = part.splice(1);
      value = value.split(';');
      if (value.length === 1) {
        value = value[0].replace('_$!<', '').replace('>!$_', '').replace('\\:', ':');
      }
      key = key.toLowerCase();
      if (key === 'x-ablabel' || key === 'x-abadr') {
        return this.addTypeProperty(this.currentDatapoint, value.toLowerCase());
      } else {
        this.handleProperties(this.currentDatapoint, properties);
        if (key === 'x-abdate') {
          key = 'about';
        }
        if (key === 'x-abrelatednames') {
          key = 'relation';
        }
        if (key === 'adr') {
          if (Array.isArray(value)) {
            value = value.map(VCardParser.unescapeText);
          } else {
            value = ['', '', VCardParser.unescapeText(value), '', '', '', ''];
          }
        }
        this.currentDatapoint['name'] = key.toLowerCase();
        return this.currentDatapoint['value'] = value;
      }
    };

    VCardParser.prototype.handleComplexLine = function(line) {
      var all, key, properties, value, _ref, _ref1;
      _ref = line.match(regexps.complex), all = _ref[0], key = _ref[1], properties = _ref[2], value = _ref[3];
      this.storeCurrentDatapoint();
      this.currentDatapoint = {};
      value = value.split(';');
      if (value.length === 1) {
        value = value[0];
      }
      key = key.toLowerCase();
      if (key === 'photo') {
        this.currentContact['photo'] = value;
        return this.currentDatapoint = null;
      } else if ((_ref1 = !key) === 'email' || _ref1 === 'tel' || _ref1 === 'adr' || _ref1 === 'url') {
        return this.currentDatapoint = null;
      } else {
        this.currentDatapoint['name'] = key;
        if (key === 'adr') {
          if (Array.isArray(value)) {
            value = value.map(VCardParser.unescapeText);
          } else {
            value = ['', '', VCardParser.unescapeText(value), '', '', '', ''];
          }
        }
        this.handleProperties(this.currentDatapoint, properties.split(';'));
        if (this.currentDatapoint.encoding === 'quoted-printable') {
          if (Array.isArray(value)) {
            value = value.map(VCardParser.unquotePrintable);
          } else {
            value = VCardParser.unquotePrintable(value);
          }
          delete this.currentDatapoint.encoding;
        }
        return this.currentDatapoint.value = value;
      }
    };

    VCardParser.prototype.handleProperties = function(dp, properties) {
      var all, match, pname, previousValue, property, pvalue, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = properties.length; _i < _len; _i++) {
        property = properties[_i];
        if (match = property.match(regexps.property)) {
          all = match[0], pname = match[1], pvalue = match[2];
          pvalue = pvalue.toLowerCase();
          previousValue = dp[pname.toLowerCase()];
          if ((previousValue != null) && previousValue !== 'internet') {
            pvalue = "" + previousValue + " " + pvalue;
          }
        } else if (property === 'PREF') {
          pname = 'pref';
          pvalue = true;
          if (dp.type != null) {
            dp.type = "" + dp.type + " " + (property.toLowerCase());
          } else {
            dp.type = property.toLowerCase();
          }
        } else {
          pname = 'type';
          if (dp.type != null) {
            pvalue = "" + dp.type + " " + (property.toLowerCase());
          } else {
            pvalue = property.toLowerCase();
          }
        }
        if (pname === 'type' && pvalue === 'pref') {
          pname = 'pref';
          pvalue = true;
        }
        _results.push(dp[pname.toLowerCase()] = pvalue);
      }
      return _results;
    };

    return VCardParser;

  })();

  VCardParser.unquotePrintable = function(value) {
    var error;
    value = value || '';
    try {
      return utf8.decode(quotedPrintable.decode(value));
    } catch (_error) {
      error = _error;
      return value;
    }
  };

  VCardParser.escapeText = function(value) {
    var text;
    if (value == null) {
      return value;
    } else {
      text = value.replace(/([,;\\])/ig, "\\$1");
      text = text.replace(/\n/g, '\\n');
      return text;
    }
  };

  VCardParser.unescapeText = function(t) {
    var s;
    if (t == null) {
      return t;
    } else {
      s = t.replace(/\\n/ig, '\n');
      s = s.replace(/\\([,;\\])/ig, "$1");
      return s;
    }
  };

  VCardParser.toVCF = function(model, picture, android) {
    var currentType, dp, folded, formattedType, i, itemCounter, key, line, out, pictureString, prop, type, types, uid, uri, value, _i, _j, _len, _len1, _ref, _ref1, _ref2;
    if (picture == null) {
      picture = null;
    }
    if (android == null) {
      android = true;
    }
    itemCounter = 0;
    out = ["BEGIN:VCARD"];
    out.push("VERSION:3.0");
    uri = model.carddavuri;
    uid = (uri != null ? uri.substring(0, uri.length - 4) : void 0) || model.id;
    out.push("UID:" + uid);
    _ref = ['fn', 'bday', 'org', 'title', 'url', 'note'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      prop = _ref[_i];
      value = model[prop];
      if (value) {
        value = VCardParser.escapeText(value);
      }
      if (value) {
        out.push("" + (prop.toUpperCase()) + ":" + value);
      }
    }
    if (model.n != null) {
      out.push("N:" + model.n);
    }
    if ((model.tags != null) && model.tags.length > 0) {
      value = model.tags.map(VCardParser.escapeText).join(',');
      out.push("CATEGORIES:" + value);
    }
    _ref1 = model.datapoints;
    for (i in _ref1) {
      dp = _ref1[i];
      key = dp.name.toUpperCase();
      type = ((_ref2 = dp.type) != null ? _ref2.toUpperCase() : void 0) || null;
      value = dp.value;
      if (Array.isArray(value)) {
        value = value.map(VCardParser.escapeText);
      } else {
        value = VCardParser.escapeText(value);
      }
      formattedType = "";
      if (type != null) {
        types = type.split(' ');
        for (_j = 0, _len1 = types.length; _j < _len1; _j++) {
          currentType = types[_j];
          formattedType += ";TYPE=" + currentType;
        }
      }
      switch (key) {
        case 'ABOUT':
          if (type !== 'DIED' && type !== 'ANNIVERSARY') {
            out.push("X-" + type + ":" + value);
          } else {
            itemCounter++;
            out.push("item" + itemCounter + ".X-ABDATE:" + value);
            formattedType = capitalizeFirstLetter(type);
            out.push("item" + itemCounter + ".X-ABLabel:" + formattedType);
            if (android) {
              out.push(getAndroidItem('contact_event', type, value));
            }
          }
          break;
        case 'OTHER':
          out.push("X-EVENT" + formattedType + ":" + value);
          break;
        case 'CHAT':
          if (type === 'SKYPE') {
            out.push("X-" + 'SKYPE-USERNAME' + ":" + value);
          }
          out.push("X-" + type + ":" + value);
          break;
        case 'URL':
          itemCounter++;
          out.push("item" + itemCounter + ".URL:" + value);
          if (type !== 'PROFILE' && type !== 'BLOG') {
            formattedType = capitalizeFirstLetter(type);
            out.push("item" + itemCounter + ".X-ABLabel:_$!<" + formattedType + ">!$_");
          } else {
            out.push("item" + itemCounter + ".X-ABLabel:" + type);
          }
          break;
        case 'RELATION':
          itemCounter++;
          out.push("item" + itemCounter + ".X-ABRELATEDNAMES:" + value);
          formattedType = capitalizeFirstLetter(type);
          out.push("item" + itemCounter + ".X-ABLabel:_$!<" + formattedType + ">!$_");
          if (android) {
            line = getAndroidItem('relation', type, value);
            if (line) {
              out.push(line);
            }
          }
          break;
        case 'ADR':
          out.push("" + key + formattedType + ":" + (value.join(';')));
          break;
        default:
          out.push("" + key + formattedType + ":" + value);
      }
    }
    if (picture != null) {
      folded = picture.match(/.{1,75}/g).join('\n ');
      pictureString = "PHOTO;ENCODING=B;TYPE=JPEG;VALUE=BINARY:\n " + folded;
      out.push(pictureString);
    }
    out.push("END:VCARD");
    return out.join("\n") + "\n";
  };

  VCardParser.nToFN = function(n) {
    var familly, given, middle, parts, prefix, suffix;
    n = n || [];
    familly = n[0], given = n[1], middle = n[2], prefix = n[3], suffix = n[4];
    parts = [prefix, given, middle, familly, suffix];
    parts = parts.filter(function(part) {
      return (part != null) && part !== '';
    });
    return parts.join(' ');
  };

  VCardParser.fnToN = function(fn) {
    fn = fn || '';
    return ['', fn, '', '', ''];
  };

  VCardParser.fnToNLastnameNFirstname = function(fn) {
    var familly, given, middle, parts, _i, _ref;
    fn = fn || '';
    _ref = fn.split(' '), given = _ref[0], middle = 3 <= _ref.length ? __slice.call(_ref, 1, _i = _ref.length - 1) : (_i = 1, []), familly = _ref[_i++];
    parts = [familly, given, middle.join(' '), '', ''];
    return parts;
  };

  VCardParser.adrArrayToString = function(value) {
    var countryPart, flat, streetPart, structuredToFlat;
    value = value || [];
    structuredToFlat = function(t) {
      t = t.filter(function(part) {
        return (part != null) && part !== '';
      });
      return t.join(', ');
    };
    streetPart = structuredToFlat(value.slice(0, 3));
    countryPart = structuredToFlat(value.slice(3, 7));
    flat = streetPart;
    if (countryPart !== '') {
      flat += '\n' + countryPart;
    }
    return flat;
  };

  VCardParser.adrStringToArray = function(s) {
    s = s || '';
    return ['', '', s, '', '', '', ''];
  };

  if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
    module.exports = VCardParser;
  } else {
    window.VCardParser = VCardParser;
  }

}).call(this);
